[toolchain]
anchor_version = "1.1.2"
solana_version = "3.1.10"
package_manager = "npm"

[features]
resolution = true

[programs.localnet]
comfi = "3vzvgpB5MWB2cHGPRzWtRmKeQtZVfkffu6uygjoNDDYP"
user_account = "7FHwv2r8R8avPiqq7ZaAUx3XYozt36F1zFfoNMHZeJ57"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/comfi", "programs/user-account"]
types = "target/types"
