[package]
name = "comfi"
version = "0.1.0"
description = "ComFi pooled-USDC governance program"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "comfi"

[features]
default = []
no-entrypoint = []
cpi = ["no-entrypoint"]
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]

[dependencies]
anchor-lang = { version = "1.1.2", features = ["init-if-needed"] }
anchor-spl = "1.1.2"
solana-instructions-sysvar = "3.0.1"
solana-sdk-ids = "3.1.0"
